language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

script:
  - ./gradlew build

notifications:
  slack:
    secure: cTV+Y4DUqcEksYzJpaJHMOcY8neMRTjoLqg0wSYlHBmrGuXEAWczhm5l2Ku48GwCSLd1KsWElvl1avHAzHdPgmMO69VDbGJxOujmDLQL8RAUalfN/FvOqYq8WlshMv1ENhrUCXi3xfJAgqqEbwA3UBBYAuF7nm6HfgKYxIJQ9YhFEPyi/dPRNnPkqyLA9iTl+dzsKjLnrt8SgPdiYGeXbkGDwCb2mXgqTbHf8LG2C9ehIDmxNLeXZTk9GBEF8PY7mcmxqiULjqYrUGEMTwqnIPvZKNxdP+6x3xnN+7Ts+rsiLSc1IemkuoeHnCPmCVLKInVgwQjroAGNC0rFqVug13UD7z3Tkrvv/g5ML7DSHscK1m/Kiv89GABLURWpD4n0z2z+TTfN865rmP9+oNQ2sJcl+HTdawipZScySEhCbxnyt8qCvxeGjsEWnGhDbZCk324fvM5xDbHs1ftKtgMDygG+p+SeTU5WJsJf3v73SXkeQqqwemmjp0bz8ME98ZrsGNQfAuzMrZbwKhvHnRaEaFK7NiXYrA/DVnpv+CmCVO5kAm2Z2/C+vGG/q0+ZxNDB+sAX+k+k6BLL1elbrUiMtBx8ArBPWOnDkKcqrQOLhRkZDpG8OfY/GTOr9/wNV/tNWYEgkMo+c3owzNuDW/Tu1HX3DNLs7fMw90zMf0WhVt0=
    rooms:
      - permission-nanny:ZgNsHtoW3DcEvUmWtAFmIu1l#bot-travis
